version: '3.8'

services:
  vault:
    image: hashicorp/vault:1.19.4
    container_name: vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8200
      - VAULT_API_ADDR=http://<Vault-Addr>:<Vault-Port>

    ports:
      - "192.168.112.130:8200:8200"
    cap_add:
      - IPC_LOCK
    command: server -dev -dev-listen-address=0.0.0.0:8200
